# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (C) 2025 Cranky Kernel <crankykernel@proton.me>

[[providers]]
name = "Example Provider 1"
url = "https://your-server.com:port/player_api.php"
username = "your-username"
password = "your-password"

[[providers]]
name = "Example Provider 2"
url = "https://another-server.com:port/player_api.php"
username = "your-username-2"
password = "your-password-2"

[player]
command = "mpv"
args = ["--fs", "--quiet"]

[cache]
ttl_seconds = 3600
max_entries = 1000

[ui]
page_size = 20
search_debounce_ms = 300